# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdv/edge/comfort/hvac/v1/hvac.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#sdv/edge/comfort/hvac/v1/hvac.proto\x12\x18sdv.edge.comfort.hvac.v1\"H\n\x12SetAcStatusRequest\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".sdv.edge.comfort.hvac.v1.AcStatus\"\x12\n\x10SetAcStatusReply\",\n\x15SetTemperatureRequest\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\"\x15\n\x13SetTemperatureReply*\x1b\n\x08\x41\x63Status\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x32\xe1\x01\n\x04Hvac\x12g\n\x0bSetAcStatus\x12,.sdv.edge.comfort.hvac.v1.SetAcStatusRequest\x1a*.sdv.edge.comfort.hvac.v1.SetAcStatusReply\x12p\n\x0eSetTemperature\x12/.sdv.edge.comfort.hvac.v1.SetTemperatureRequest\x1a-.sdv.edge.comfort.hvac.v1.SetTemperatureReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdv.edge.comfort.hvac.v1.hvac_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACSTATUS']._serialized_start=228
  _globals['_ACSTATUS']._serialized_end=255
  _globals['_SETACSTATUSREQUEST']._serialized_start=65
  _globals['_SETACSTATUSREQUEST']._serialized_end=137
  _globals['_SETACSTATUSREPLY']._serialized_start=139
  _globals['_SETACSTATUSREPLY']._serialized_end=157
  _globals['_SETTEMPERATUREREQUEST']._serialized_start=159
  _globals['_SETTEMPERATUREREQUEST']._serialized_end=203
  _globals['_SETTEMPERATUREREPLY']._serialized_start=205
  _globals['_SETTEMPERATUREREPLY']._serialized_end=226
  _globals['_HVAC']._serialized_start=258
  _globals['_HVAC']._serialized_end=483
# @@protoc_insertion_point(module_scope)
