#!/bin/sh
#********************************************************************************
# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License 2.0 which is available at
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#*******************************************************************************/

if [ "$1" = "--help" ]; then
    echo "Usage: $0 <can_if> {timeout}"
    echo "  can_if - use specified can interface. Default: can0"
    echo "  timeout - delay between random frames. default 1000ms."
    exit 0
fi

CAN=$1
[ -z "$CAN" ] && CAN="can0"

TIMEOUT=$2
[ -z "$TIMEOUT" ] && TIMEOUT=1000

cangen -v $CAN -L 8 -I 712 -D r -g $TIMEOUT


