#!/bin/bash
#********************************************************************************
# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License 2.0 which is available at
# http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#*******************************************************************************/


if [ "$1" = "--help" ]; then
    echo "Usage: $0 <can_if> {iterations} {verbose}"
    echo "	can_if - use specified can interface. Default: vcan0"
    echo "	iterations - runs pos change [0..100]-[100..0] in a loop. 0=infinite, Default: 0"
	echo "	verbose - if 3rd arg is provided - prints generated cansend commands"
    exit 0
fi

CAN=$1
[ -z "$CAN" ] && CAN="vcan0"

ITERATIONS="$2" # optional, assume infinite
[ -z "$ITERATIONS" ] && ITERATIONS=0

VERBOSE="$3"

echo "# Running $ITERATIONS interations on: $CAN ..."
iter=0
while [ $ITERATIONS -eq 0 ] || [ $iter -lt $ITERATIONS ]; do
	echo
	echo "### Sending SECU1_STAT [ MOTOR1_MOV_STATE: 'INC', MOTOR1_LEARNING_STATE: 'learned', MOTOR1_POS: 0..100 ]"
	for pos in `seq 0 +1 100`; do
		frame=`printf "cansend $CAN 712#46.44.%02X.00.00.00.00.00" $pos`
		[ -n "$VERBOSE" ] && echo "$frame"
		`$frame`
		sleep 0.01
		`$frame`
		sleep 0.01
	done

	sleep 5

	[ -n "$VERBOSE" ] && echo
	echo "### Sending SECU1_STAT [ MOTOR1_MOV_STATE: 'DEC', MOTOR1_LEARNING_STATE: 'learned', MOTOR1_POS: 100..0 ]"
	for pos in `seq 100 -1 0`; do
		frame=`printf "cansend $CAN 712#45.44.%02X.00.00.00.00.00" $pos`
		[ -n "$VERBOSE" ] && echo "$frame"
		`$frame`
		sleep 0.01
		`$frame`
		sleep 0.01
	done
	[ -n "$VERBOSE" ] && echo

	((iter=iter+1))
done
