# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: dev-container-build-prerelease

on:
  push:
    paths:
      - "tools/Dockerfile"
      - ".github/workflows/dev_container_build_prerelease.yml"
  workflow_dispatch:

jobs:
  call-dev-container-build:
    uses: ./.github/workflows/dev_container_build.yml
    with:
      tag: "prerelease"
